files_name = {
    "universal": [
        ["file 1", "audio  (1)"],
        ["file 2", "audio  (2)"],
        ["file 3", "audio  (3)"],
        ["file 4", "audio  (4)"],
        ["file 5", "audio  (5)"],
        ["file 6", "audio  (6)"],
        ["file 3", "3"],
        ["file 3", "3"],
        ["file 3", "3"],
        ["file 3", "3"],
        ["file 3", "3"],
        ["file 3", "3"],
        ["file 3", "3"],
        ["file 3", "3"],
        ["file 3", "3"],
        ["file 3", "3"],
        ["file 3", "3"],
        ["file 3", "3"],
        ["file 3", "3"],
        ["file 3", "3"],
        ["file 4", "3"],
    ],
    "trade": [
        ["test gs", "audtg"],
        ["audio name", "file path"],
        ["audio name", "file path"],
    ],
    "nft": [
        ["audio name", "file path"],
        ["audio name", "file path"],
        ["audio name", "file path"],
    ],
    "exchange": [
        ["audio name", "file path"],
        ["audio name", "file path"],
        ["audio name", "file path"],
    ],
    "casino": [
        ["audio name", "file path"],
        ["audio name", "file path"],
        ["audio name", "file path"],
    ],
    "escort": [
        ["audio name", "file path"],
        ["audio name", "file path"],
        ["audio name", "file path"],
    ],
    "antik": [
        ["audio name", "file path"],
        ["audio name", "file path"],
        ["audio name", "file path"],
    ],
    "narko": [
        ["audio name", "file path"],
        ["audio name", "file path"],
        ["audio name", "file path"],
    ],
}
